---
title: "random"
author: "Brian Murphy"
date: "3/10/2021"
output: html_document
---

```{r setup}
library(tidyverse)
library(plotly) # N.B. Requires the Cairo package
library(spotifyr)
library(compmus)
library(dplyr)
library(gridExtra)
library(ggplot2)
```




```{r}
pata_pata <-
  get_tidy_audio_analysis("6Sy9BUbgFse0n0LPA5lwy5") %>%
  select(segments) %>%
  unnest(segments)
```

```{r}
pata_pata %>%
  mutate(loudness_max_time = start + loudness_max_time) %>%
  arrange(loudness_max_time) %>%
  mutate(delta_loudness = loudness_max - lag(loudness_max)) %>%
  ggplot(aes(x = loudness_max_time, y = pmax(0, delta_loudness))) +
  geom_line() +
  xlim(0, 30) +
  theme_minimal() +
  labs(x = "Time (s)", y = "Novelty")
```

```{r}
pata_pata %>%
  mutate(pitches = map(pitches, compmus_normalise, "clr")) %>%
  arrange(start) %>%
  mutate(pitches = map2(pitches, lag(pitches), `-`)) %>%
  slice(-1) %>%
  compmus_gather_chroma() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = pmax(0, value)
    )
  ) +
  geom_tile() +
  scale_fill_viridis_c(guide = "none") +
  xlim(0, 30) +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_classic()
```

***

<iframe src="https://open.spotify.com/embed/track/6lSxM9BKcEZBSDKl2VODsF" width="582" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
